source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "jekyll"
gem 'bootstrap', '~> 4.5.3'
# TODO: use official gem
#gem "just-the-docs", path: "/Users/kevinlin/projects/dendronv2/dendron-just-the-docs/"